name: 'Hugo build and Firebase Deploy'
description: 'Builds the site using Hugo, and deploy it to Firebase Hosting'
branding:
  icon: 'arrow-up-circle'  
  color: 'green'
inputs:
  firebase-token:
    description: 'Firebase token (obtained via firebase tools -- firebase login:ci)'
    required: true
  alias:
    description: 'Firebase project alias.'
    required: true
  working-directory:
    description: 'The relative path to the directory that points to hugo root. Repo root is used by default.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.firebase-token }}
    - ${{ inputs.alias }}
    - ${{ inputs.working-directory }}
